<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
define('ROOT', dirname(__FILE__));
define('PATH_TO_PARSINGTOOL', "https://pt.metal100.ru");
define('METALTORG_USER_ID', 40953);
define('METALINFO_USER_ID', 40955);
define('TRUBAMET_USER_ID', 40956);
define('TRUBI_BU_USER_ID', 40957);
define('STROY_NET_USER_ID', 27);
define('STROI_BAZA_RU_USER_ID', 8815);
define('STROY_BEST_RU_USER_ID', 8817);
define('FREE_ADS_RF_USER_ID', 8818);
define('INFORM_BYURO_ID', 31);
define('VASHDOM_ID', 101);
define('ARMATURSHIKI_STROIM_ID', 593);
define('ARMATURSHIKI_METALL_ID', 54645);
define('ISSERVER', true);
include_once ROOT . '/extension/html_dom/simple_html_dom.php';
include_once ROOT . '/extension/htmlpurifier-4.5.0/library/HTMLPurifier.auto.php';
include_once ROOT . '/mainclasses/class.WorkDb.php';
include_once ROOT . '/adParser/inc/CreateAd.php';
include_once ROOT . '/adParser/inc/Ad.php';
include_once ROOT.'/function.php';
